dashboard_portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = "dashboard"

urlpatterns = [
	url(r'^$', views.centerLoginPage, name='login'),
	#url(r'^portal/', views.trainingCenterLogin, name='trainingcenterlogin'),
	url(r'^dashboard/', views.dashboardView, name='dashboardview'),
	url(r'^dashboard/updated/', views.updateCenterInfo, name='update'),
	url(r'^logout/', views.logout, name='logout'),
]

dashboard_portal/models.py
from django.db import models

# Create your models here.

dashboard_portal/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from api.models import TrainingCenter
import json
import requests

def centerLoginPage(request):     ##login
	return render(request, 'pmkvy_test/login.html')
"""
def trainingCenterLogin(request):          ##dashboard
	
	url = "http://9a3a0b42.ngrok.io/api/singletrainingcenter/"

	center_id = request.POST["centerid"]

	data = {
		"center_id":center_id
	}

	response = requests.post(url, data=data)
	#return HttpResponse(response.text)
	if (response.text == "false") or (response.text == "False") and (request.session.get("center_id", None)):
		return HttpResponseRedirect("/tc_login/")
	else:
		request.session['center_id']=center_id
		jsonobject = json.loads(response.text)

		finalresult = jsonobject["data"]
		return HttpResponseRedirect(reverse("/tc_login/dashboard/", args=(center_id,)))

		#return render(request, 'pmkvy_test/dashboard.html', {'result':finalresult})
"""
def dashboardView(request):

	url = "http://localhost:8000/api/singletrainingcenter/"

	try:
		if request.session.get('center_id'):
			center_id = request.session['center_id']
		else:	
			#return HttpResponseRedirect('/tc_login/')
			center_id = request.POST["centerid"]
	except:
		return HttpResponseRedirect('/tc_login/')		

	data = {
		"center_id":center_id
	}

	response = requests.post(url, data=data)

	jsonobject = json.loads(response.text)
	finalresult = jsonobject["data"]
	if response.text == "false":
		return HttpResponseRedirect("/tc_login/")
	else:
		request.session['center_id'] = center_id	
		if request.session.get('center_id'):
			print("Logged in"+request.session['center_id'])
			"""
			request.session["alldata"]["c_name"] = finalresult["c_name"]
			request.session["alldata"]["c_id"] = finalresult["c_id"]
			request.session["alldata"]["c_addr"] = finalresult["c_addr"]
			request.session["alldata"]["c_partner_name"] = finalresult["c_partner_name"]
			request.session["alldata"]["c_poc_name"] = finalresult["c_poc_name"]
			request.session["alldata"]["c_poc_email"] = finalresult["c_poc_email"]
			"""


			return render(request, 'pmkvy_test/dashboard.html', {'result':finalresult})
		else:
			print("Visitor")
			return HttpResponseRedirect("/tc_login/")

def logout(request):
	del request.session['center_id']
	return HttpResponse(True)

"""
def dashboardPortal(request):
	url = "http://9a3a0b42.ngrok.io/api/singletrainingcenter/"

	center_id = request.session['center_id']
	data = {
		"center_id":center_id
	}

	response = requests.post(url, data=data)
	#return HttpResponse(response.text)
	jsonobject = json.loads(response.text)
	print(jsonobject)
	finalresult = jsonobject["data"]
	request.session['alldata'] = jsonobject
	return render(request, 'pmkvy_test/dashboard.html', {'result':finalresult})
"""
def updateCenterInfo(request):

	if not request.session['alldata']:
		c_name = request.POST["c_name"]
		c_id = request.POST["c_id"]
		c_address = request.POST["c_addr"]
		c_partner_name = request.POST["c_partner_name"]
		c_poc_name = request.POST["c_poc_name"]
		c_poc_email = request.POST["c_poc_email"]
	"""	
	else:
		c_name = request.session["alldata"]["c_name"]
		c_id = request.session["alldata"]["c_id"]
		c_address = request.session["alldata"]["c_addr"]
		c_partner_name = request.session["alldata"]["c_partner_name"]
		c_poc_name = request.session["alldata"]["c_poc_name"]
		c_poc_email = request.session["alldata"]["c_poc_email"]
	"""
	training_center = TrainingCenter.objects.get(center_id=c_id)

	training_center.training_center_name = c_name
	training_center.address = c_address
	#training_center.training_partner = c_partner_name
	training_center.center_poc_name = c_poc_name
	training_center.center_poc_email = c_poc_email
	training_center.save()

	#return HttpResponseRedirect('/tc_login/dashboard/')
	dashboardView(request)
	#return render(request, 'pmkvy_test/dashboard.html', {'updateresult':'Updated Successfully'})

dashboard_portal/templates/pmkvy_test/dashboard.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<script language="Javascript" src="jquery.js"></script>
		<!--script type="text/JavaScript" src='state.js'></script-->
	    <link rel="stylesheet" type="text/css" href="{% static 'pmkvy_test/dashboard.css' %}">
		<!--link rel="stylesheet" href="base_style.css"-->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Work+Sans">
		<!--script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script-->
		<link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
				
		<script type = "text/javascript" src = "https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
		
		<title>Website</title>
		
		<script>
			setInterval(function() { ObserveInputValue($('#c_name').val()); }, 1);
		</script>

	</head>

	<body>
	<nav>
		<div class="container">
				<a href="#" class="nav-logo">
					<div class="nav-logo-img"></div>
				</a>
				<ul>
					<li><a href="#" class="active">Home</a></li><!--
					--><li><a href="#">About</a></li><!--
					--><li><a href="#">Work</a></li><!--
					--><li class="dropdown">
							<a href="javascript:void(0)" class="dropbtn">Dropdown</a>
							<div class="dropdown-content">
								<a href="#">Link 1</a>
								<a href="#">Link 2</a>
								<a href="#">Link 3</a>
							</div>
						</li><!--
					--><li><a href="#">Contact</a></li>
				</ul>
			</div>
		</nav>

		<div class="main-wrapper">
				<div class="left-panel">
					<div class="left-panel-container">
						<ul>
							<a href="#"><li>Update Center Detail </li></a>
							<a href="#"><li>Manage Student List</li></a>
							<a href="#"><li>Update Course/Batch Details</li></a>
							<a href="#"><li>Add News/Notice</li></a>
						</ul>
					</div>
				</div>
				<div class="right-panel">
					<div class="update-center-info-div">	
						<div class="module-header">
							Update Center Information
						</div>
					</div>
					<form action="{% url 'dashboard:update' %}" method="post"> 
						{% csrf_token %}
						<div class="update-center-info-div md-whiteframe-2dp">
							<table>
								<div class="module-header-branch">
									General Center Information
								</div>	
								<tr>
									<td>Center Name</td>
									<td><input id="c_name" type="text" value="{{ result.training_center_name }}"></td>
								</tr>
								<tr>
									<td>Center Id</td>
									<td class="table-data-right"><input id="c_id" type="text" value="{{ result.center_id }}" disabled></td>
								</tr>
								<tr>
									<td>Center Address</td>
									<td><textarea name="address" id="c_addr" cols="30" rows="4">{{ result.address }}</textarea></td>
								</tr>
							</table>
						</div>
						<div class="update-center-info-div md-whiteframe-2dp">
							<table>
								<div class="module-header-branch">
									Training Partner Information
								</div>	
								<tr>
									<td>Name</td>
									<td><input id="c_partner_name" type="text" value="{{ result.training_partner }}"></td>
								</tr>
								<!--tr>
									<td>Email</td>
									<td><input id="c_partner_email" type="text"></td>
								</tr-->
							</table>
						</div>
						<div class="update-center-info-div md-whiteframe-2dp">
							<table>
								<div class="module-header-branch">
									Contact Details
								</div>	
								<tr>
									<td>Center POC Name</td>
									<td><input id="c_poc_name" type="text" value="{{ result.center_poc_name }}"></td>
								</tr>
								<tr>
									<td>Center POC Email</td>
									<td><input id="c_poc_email" type="text" value="{{ result.center_poc_email }}"></td>
								</tr>
							</table>
						</div>
						<input id="c_button" class="update-button md-whiteframe-4dp" type="submit" value="Update" onclick="saveall()">
					</div>
				</form>		
		</div>
	</body>
</html>	

dashboard_portal/templates/pmkvy_test/login.html
{% load static %}

<link rel="stylesheet" href="{% static 'pmkvy_test/logincss.css' %}"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Work+Sans">
<!--link rel="stylesheet" href="{% static 'pmkvy/bootstrap-social.css' %}"/>
<link rel="stylesheet" href="{% static 'pmkvy/fontawesome-webfont.svg' %}"/-->

<body>
	<nav>
		<div class="container">
			<a href="#" class="nav-logo">LOGO</a>
			<ul>
				<li><a href="#" class="active">Home</a></li><!--
				--><li><a href="#">About</a></li><!--
				--><li><a href="#">Work</a></li><!--
				--><li class="dropdown">
						<a href="javascript:void(0)" class="dropbtn">Dropdown</a>
						<div class="dropdown-content">
							<a href="#">Link 1</a>
							<a href="#">Link 2</a>
							<a href="#">Link 3</a>
						</div>
					</li><!--
				--><li><a href="#">Contact</a></li>
			</ul>
		</div>
	</nav>

<div class="main-wrapper">
	<div class="container">
		<div class="section1">
			<!--div class="other-login">
				<a href="/accounts/twitter/login/?process=login" class="md-whiteframe-10dp btn btn-social-icon btn-twitter twitter"><span class="fa fa-twitter"></span><img
                        src="http://www.freeiconspng.com/uploads/twitter-icon-9.png" alt="twitter" width="100%" height="100%"></a>
                <br><br>
				<a href="#" class="md-whiteframe-10dp btn btn-social-icon btn-google google"><span class="fa fa-google"><img src="http://www.freeiconspng.com/uploads/google-plus-logo-4.png" alt="google" width="100%" height="100%"></a>
                <br><br>
                <a href="#" class="md-whiteframe-10dp btn btn-social-icon btn-openid aadhar"><span class="fa fa-google">A</a>
			</div-->
			<div class="loginpanel md-whiteframe-3dp" id="loginpanel">
				<div class="title md-whiteframe-4dp">
					<h3 style="position:relative;top:15px;font-family:Roboto;">Login Panel</h3>
				</div><br><br>
				<form action="{% url 'dashboard:dashboardview' %}" method="post">
					{% csrf_token %}
					<div class="mode">
						<select name="selector" id="selector">
							<option value="admin">Center Admin</option>
							<option value="authority">Higher Authority</option>
						</select>
					</div>	
					<div class="field">
						<input type="text" id="username" placeholder="Center Id" name="centerid">
						<div class="line" id="line"></div>
					</div><br><br>
					<!--div class="field">
						<input type="password" id="password" placeholder="Password" name="password">
						<div class="line" id="line"></div>
					</div><br><br-->
					<button type="submit" id="submit" class="btn-primary md-whiteframe-5dp">Login</button>
				</form>
			</div>
		</div>
	</div>
</div>
</body>